spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.leiduo.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: microservicecloud-dept   #为这个服务取名，非常重要！！！！！
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB03?serverTimezone=Asia/Shanghai 
    username: root
    password: 1234
    dbcp2:
      min-idle: 5         #最小连接数
      initial-size: 5    #初始化连接数
      max-total: 10      #最大连接数
      max-wait-millis: 200  #等待连接最长的超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true
info:
  app.name: leiduo-microservicecloud
  company.name: leiduo-study
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---